INSERT INTO products (name, price) VALUES
                                       ('Laptop', 1200.50),
                                       ('Mouse', 25.75),
                                       ('Teclado Mecánico', 80.00),
                                       ('Monitor', 250.00),
                                       ('Silla Gamer', 300.00),
                                       ('Disco SSD 1TB', 150.00),
                                       ('Cámara Web', 60.00),
                                       ('Micrófono', 90.00),
                                       ('Audífonos Bluetooth', 110.00),
                                       ('Router WiFi', 45.00),
                                       ('Tableta Gráfica', 180.00),
                                       ('Lámpara LED', 35.00),
                                       ('Impresora Láser', 220.00),
                                       ('Control de Xbox', 70.00),
                                       ('Memoria RAM 16GB', 130.00);